<?php
/**
 * @file
 * This module works with archival data for selected blazars
 *
 *
 * General documentation is available at
 * @link database Database abstraction layer documentation @endlink and
 * at @link http://drupal.org/node/310069 @endlink.
 */

/**
 * @defgroup polar
 * @ingroup RoboPol
 * @{
 * General documentation is available at
 * @link database.inc database abstraction layer documentation @endlink and
 * at @link http://drupal.org/node/310069 Database API @endlink.
 *
 */

/**
 * This function converts a string to a float no matter is the decimal separator dot (.)
 * or comma (,). It also converts integers correctly. It takes the digits from the beginning
 * of the string and ignores all other characters.
 */

/**
 * Implements hook_help().
 *
 * Show some help on each form provided by this module.
 */
function polar_help($path) {
  $output = '';
  switch ($path) {
    case 'RoboPol/polar':
      $output = t('');
      break;
    case 'RoboPol/polar/add':
      $output = t('');
      break;
    case 'RoboPol/polar/list':
      $output = t('Here you can find some more links for archives.');
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 *
 * Set up calls to drupal_get_form() for all our example cases.
 */
function polar_menu() {
  $items = array();

  $items['RoboPol/polar'] = array(
    'title' => 'Polarimetry data archive',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('polar_form_get'),
    'access callback' => TRUE,
    'file' => 'ajax_dep_dropdown.inc'
  );
  $items['RoboPol/polar/get_data'] = array(
    'title' => 'Get data',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['RoboPol/polar/add'] = array(
    'title' => 'Add data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('polar_form_add'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -9,
  );
  // See add_obj.inc.
  $items['RoboPol/polar/add_object'] = array(
    'title' => 'Add object',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('polar_form_add_object'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'add_obj.inc',
    'weight' => -8,
  );
  $items['RoboPol/polar/delete'] = array(
    'title' => 'Remove data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('polar_form_delete'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'delete_data.inc',
    'weight' => -7,
  );
  // A menu callback is required when using ajax outside of the Form API.
  $items['pa_ajax_link_callback'] = array(
    'page callback' => 'pa_ajax_link_response',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    //'file' => 'ajax_example_misc.inc',
  );
  //$items['VO/polar/list'] = array(
  //  'title' => 'Other archives',
  //  'page callback' => 'drupal_get_form',
  //  'page arguments' => array('polar_form_list'),
  //  'access callback' => TRUE,
  //  'type' => MENU_NORMAL_ITEM,
  //  'weight' => -8,
  //);
  return $items;
}

/**
 * Query to the database to get photometric data for download.
 */
function polar_data_load_phot($form, $form_state) {
  $blazar_id = $form_state['values']['name'];
  $JDstart   = $form_state['values']['JDstart'];
  $JDend     = $form_state['values']['JDend'];

  if (empty($JDstart)) $JDstart = 0;
  if (empty($JDend))   $JDend   = 2500000; //Just a big number

  // Read all fields from the polar_data table.
  $select = db_select('polar_data', 'c');
  $select->orderBy('jd', 'ASC');
  $select->fields('c')
         ->condition('blazar_id', $blazar_id,'=')
         ->condition('jd', $JDstart,'>=')
         ->condition('jd', $JDend,'<=');

  // Return the result in object format.
  return $select->execute()->fetchAll();
}

/**
 * Query to the database to get polarimetric data for download.
 */
function polar_data_load_polar($form, $form_state) {
  $blazar_id = $form_state['values']['name'];
  $JDstart   = $form_state['values']['JDstart'];
  $JDend     = $form_state['values']['JDend'];

  if (empty($JDstart)) $JDstart = 0;
  if (empty($JDend))   $JDend   = 2500000; //Just a big number

  // Read all fields from the polar_data table.
  $select = db_select('polar_polar', 'c');
  $select->orderBy('jd', 'ASC');
  $select->fields('c')
         ->condition('blazar_id', $blazar_id,'=')
         ->condition('jd', $JDstart,'>=')
         ->condition('jd', $JDend,'<=');

  // Return the result in object format.
  return $select->execute()->fetchAll();
}


function polar_file_download($filename, $mimetype='application/octet-stream') {
  if (file_exists($filename)) {
    header($_SERVER["SERVER_PROTOCOL"] . ' 200 OK');
    header('Content-Type: ' . $mimetype);
    header('Last-Modified: ' . gmdate('r', filemtime($filename)));
    header('ETag: ' . sprintf('%x-%x-%x', fileinode($filename), filesize($filename), filemtime($filename)));
    header('Content-Length: ' . (filesize($filename)));
    header('Connection: close');
    header('Content-Disposition: attachment; filename="' . basename($filename) . '";');
// Открываем искомый файл
    $f=fopen($filename, 'r');
    while(!feof($f)) {
// Читаем килобайтный блок, отдаем его в вывод и сбрасываем в буфер
      echo fread($f, 1024);
      flush();
    }
// Закрываем файл
    fclose($f);
  } else {
    header($_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
    header('Status: 404 Not Found');
  }
  exit;
}

/**
 * Get ascii data from the database.
 */
function polar_form_get_ASCII_submit($form, &$form_state) {
  //polarimetry
  //obtaining response from DB
  if ($entries = polar_data_load_polar($form, $form_state)) {
    $rows = array();
    foreach ($entries as $entry) {
      $row_el = sprintf("%5.5f ", $entry->jd);
      $row_el = $row_el.sprintf("%9s ",sprintf("%3.3f ", $entry->p));
      $row_el = $row_el.sprintf("%8s ",sprintf("%3.3f ", $entry->p_err));
      $row_el = $row_el.sprintf("%10s ",sprintf("%5.3f ", $entry->pa));
      $row_el = $row_el.sprintf("%8s ",sprintf("%3.3f ", $entry->pa_err));
      $row_el = $row_el.sprintf("%10s\r\n", $entry->tel);
      $rows[] = $row_el;
    }
  }
  else {
    drupal_set_message(t('No entries in DB available for this query.'));
  }
  $output = "";
  foreach ($rows as $row) {
    $output = $output.$row;
  }   

  $blazar_name = $form['name_fieldset']['name']['#options'][$form_state['values']['name']];
  //creating a file with data
  $filepath = file_unmanaged_save_data($output, $destination = "public://".$blazar_name.".dat", $replace = FILE_EXISTS_REPLACE);
  polar_file_download($filepath);
}

/**
 * Prepare a simple form to get data, with all the interesting fields.
 */
function old_polar_form_get($form, &$form_state) {//FIXME remove it!!!!!!!!!!!!
//old version without AJAX
  $form = array();

  $form = array(
    '#prefix' => '<div id="updateform">',
    '#suffix' => '</div>',
  );
  $form['name'] = array(
    '#type' => 'select',
    '#options' => blazars_list_load(),
    '#title' => t('Имя объекта:'),
    '#ajax' => array(
      'callback' => 'ajax_example_dependent_dropdown_callback',
      'wrapper' => 'dropdown-second-replace',
    ),
  );
  $form['JDstart'] = array(
    '#type'  => 'textfield',
    '#title' => t('От JD:'),
    '#description' => t('Leave blank, if you need the whole dataset'),
    '#size'  => 10,
  );
  $form['JDend'] = array(
    '#type'  => 'textfield',
    '#title' => t('До JD:'),
    '#size'  => 10,
  );
  $form['ASCII'] = array(
    '#type' => 'submit',
    '#value' => t('Download ASCII'),
    '#submit' => array('polar_form_get_ASCII_submit'),
  );
  $form['VOT'] = array(
    '#type' => 'submit',
    '#value' => t('Load VOT'),
    '#submit' => array('polar_form_get_VOT_submit'),
  );
  return $form;
}

/**
 * Custom validation form for the 'get data' page.
 *
 * @ingroup RoboPol
 */
function polar_form_get_validate($form, &$form_state) {
  if (!empty($form_state['values']['JDstart'])) {
    if (!is_numeric($form_state['values']['JDstart'])) {
      form_set_error('JD', t('JD start must be numeric.'));
    }
  }
  if (!empty($form_state['values']['JDend'])) {
    if (!is_numeric($form_state['values']['JDend'])) {
      form_set_error('JD', t('JD end must be numeric.'));
    }
  }
}

/** Loading list of blazar names from DB */
function blazars_list_load() {
  // Read all fields from the polar_objects table.
  $result = db_query('SELECT id,name FROM polar_objects');
  $entries = $result->fetchAll();
  $blazars_with_id = array();
  foreach ($entries as $entry) {
    $blazars_with_id[$entry->id] = $entry->name;
  }
  return $blazars_with_id;
}

/** Creates javascript with data for dygraphs library
    in case of polarimetric data request
*/
function get_data_for_plot_polar($blazar_id) {
  $js_data = '';
  $js_data = $js_data.get_data_for_plot_polar_P($blazar_id);
  $js_data = $js_data.get_data_for_plot_polar_PA($blazar_id);
  return $js_data;
}

/** Creates javascript with data for dygraphs library
    gets Polarization degree
*/
function get_data_for_plot_polar_P($blazar_id) {
  $query = "SELECT jd, p FROM polar_polar WHERE blazar_id = '";
  $query = $query.$blazar_id."'";
  $entries = db_query($query)->fetchAll();
  $js_data = '<script type="text/javascript">';
  $js_data = $js_data.'function data_nolabelp(){';
  $js_data = $js_data.'return "" +';
  foreach ($entries as $entry){
    $js_data = $js_data.'"'.$entry->jd.','.$entry->p.'\n" + ';
  }
  $js_data = rtrim($js_data,' + ');
  $js_data = $js_data.';}function datap() {';
  $js_data = $js_data.'return "Date,PD\n" + data_nolabelp();';
  $js_data = $js_data.'}</script>';
  return $js_data;
}

/** Creates javascript with data for dygraphs library
    gets Polarization position angle
*/
function get_data_for_plot_polar_PA($blazar_id) {
  $query = "SELECT jd, pa FROM polar_polar WHERE blazar_id = '";
  $query = $query.$blazar_id."'";
  $entries = db_query($query)->fetchAll();
  $js_data = '<script type="text/javascript">';
  $js_data = $js_data.'function data_nolabelpa(){';
  $js_data = $js_data.'return "" +';
  foreach ($entries as $entry){
    $js_data = $js_data.'"'.$entry->jd.','.$entry->pa.'\n" + ';
  }
  $js_data = rtrim($js_data,' + ');
  $js_data = $js_data.';}function datapa() {';
  $js_data = $js_data.'return "Date,PA\n" + data_nolabelpa();';
  $js_data = $js_data.'}</script>';
  return $js_data;
}

/** */
function get_plot_code_polar($form, $form_state) {
  $blazar_id = $form_state['values']['name'];
  $code = file_get_contents('./sites/all/modules/polar/plot_js_pol');
  $txt = get_data_for_plot_polar($blazar_id);
  $code = $code.$txt;
  $code = $code.'<div style="float: right; display: none">';
  $code = $code.'<p>Zoomed: <span id="zoomed">False</span><p/>';
  $code = $code.'<p>Zoomed X: <span id="zoomedX">False</span><p/>';
  $code = $code.'<p>Zoomed Y: <span id="zoomedY">False</span><p/></div>';
  //$code = $code.'<div id="div_g" style="width:600px; height:300px;"></div>';
  $code = $code.'<div id="div_gp" style="margin-top:20px; margin-bottom:20px; margin-left:20px; width:870px; height:300px;"></div>';
  $code = $code.'<div id="div_gpa" style="margin-top:20px; margin-bottom:20px; margin-left:20px; width:870px; height:300px;"></div>';
  return $code;
}

/**
 * Prepare a simple form to add data, with all the interesting fields.
 */
function polar_form_add($form, &$form_state) {
  //check if user allowed to add to the database
  global $user;
  if (! in_array("robopol", $user->roles)) {
    $error_text = '<font size="3" color="red">Only registered users are able to access the data!</font>';
    $form['access_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t($error_text),
      '#description' => t("Please contact RoboPol team to get the access."),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    return $form;
  }

  $explanation = "Data:";
  $form = array();

  $form = array(
    '#prefix' => '<div id="updateform">',
    '#suffix' => '</div>',
  );
  $form['name'] = array(
    '#type' => 'select',
    '#options' => blazars_list_load(),
    '#title' => t('Choose blazar name:'),
  );
  $form['my_div'] = array(
    '#markup' => $explanation . '<div id="explanationDiv"></div>',
  );
  $form['ajax_link'] = array(
    '#type' => 'link',
    '#title' => t('Possible formats'),
    // Note the /nojs portion of the href - if javascript is enabled,
    // this part will be stripped from the path before it is called.
    '#href' => 'pa_ajax_link_callback/nojs/',
    '#id' => 'ajax_link',
    '#ajax' => array(
      'wrapper' => 'explanationDiv',
      'method' => 'html',
    ),
  );
  $form['data'] = array(
    '#type'  => 'textarea',
    '#title' => '',
    '#size'  => 15,
    '#description' => t('use 999, if error unknown'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add'),
  );

  return $form;
}

/**
 * Callback for link example. FIXME move to add data file
 *
 * Takes different logic paths based on whether Javascript was enabled.
 * If $type == 'ajax', it tells this function that ajax.js has rewritten
 * the URL and thus we are doing an AJAX and can return an array of commands.
 *
 * @param $type
 *   Either 'ajax' or 'nojs. Type is simply the normal URL argument to this URL.
 *
 * @return
 *   If $type == 'ajax', returns an array of AJAX Commands.
 *   Otherwise, just returns the content, which will end up being a page.
 *
 * @ingroup ajax_example
 */
function pa_ajax_link_response($type = 'ajax') {
  $output = t("1. JD Magnitude Magnutude_error<br>");
  $output = $output.t("2. JD Magnitude Magnutude_error Telescope<br>");
  $output = $output.t("3. JD Magnitude Magnutude_error ... (22 columns)<br>");
  $output = $output.t("4. JD P PA<br>");
  $output = $output.t("5. JD P PA Telescope<br>");
  $output = $output.t("6. JD Magnitude P PA<br>");
  $output = $output.t("7. JD P P_error PA PA_error<br>");
  $output = $output.t("8. JD Magnitude P P_error PA PA_error<br>");
  $output = $output.t("9. JD Magnitude P P_error PA PA_error Telescope<br>");
  $output = $output.t("10. JD Magnitude P P_error PA PA_error FWHM<br>");
  $output = $output.t("11. JD Magnitude Magnutude_error P P_error PA PA_error Telescope<br>");
  if ($type == 'ajax') {
    $commands = array();
    // See ajax_example_advanced.inc for more details on the available commands
    // and how to use them.
    $commands[] = ajax_command_append('#explanationDiv', $output);
    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
  }
  else {
    return $output;
  }
}

/**
 * Save photometry entry in the database when submitted with polarimetric data
 * This is very close to polar_entry_insert_phot(), but i think it's
 * better to separate them
 */
function polar_entry_insert_phot_from_pol($entry,$IsWithMagErr) {
  global $user;
  $n_new_rows = 0;
  $blazar_id = $entry['blazar_name'];

  //parsing data
  $data_arr = preg_split("/((?<!\\\|\r)\n)|((?<!\\\)\r\n)/", $entry['data']);
  foreach ($data_arr as $value) {
    $value = trim ($value);
    if ($value == "") continue;
    $one_line  = preg_split("/[\s,]+/", $value);
    if ( (count($one_line) < 3)||(count($one_line) > 8) ) {
      drupal_set_message(t('Data string length must be >= 3 and <= 8'), 'error');
      return NULL;
    }
    if ($IsWithMagErr) {
      if (!(is_numeric($one_line[0]) &&
            is_numeric($one_line[1]) &&
            is_numeric($one_line[2]))) {
        if ($one_line[1]=="NaN"){
          //somtimes even Mag is not defined
          continue;
        }
        else{
          drupal_set_message(t('It seems that you give not numeric data.'), 'error');
          return NULL;
        }
      }
    }
    else {
      //Mag Err is not defined and we have Pol in the 3d column
      if (!(is_numeric($one_line[0]) &&
            is_numeric($one_line[1]))) {
        if ($one_line[1]=="NaN"){
          //somtimes even Mag is not defined
          continue;
        }
        else{
          drupal_set_message(t('It seems that you give not numeric data.'), 'error');
          return NULL;
        }
      }
      $one_line[2] = 999;
    }

    $JD[]       = floatval($one_line[0]);
    $mag[]      = floatval($one_line[1]);
    $mag_err[]  = floatval($one_line[2]);
    if(!(is_numeric(end($one_line)))) {//WARNING not safe
      //only in case of 4 rows tel is the last one
      $tel[]      = end($one_line);
    }
    else{
      $tel[]      = "Unknown";
    }
    $n_new_rows = $n_new_rows + 1;
  }

  if($n_new_rows < 1) return NULL;
  $trans_value = db_transaction();
  try {
    //fill data table
    for ( $i = 0; $i < count($JD); $i += 1) {
        $data_entry = array(
          'creator_id'  => $user->uid,
          'blazar_id'   => $blazar_id,
          'jd'          => $JD[$i],
          'mag'         => $mag[$i],
          'mag_err'     => $mag_err[$i],
          'tel'         => $tel[$i],
        );
    
        $query = db_merge('polar_data')
                   ->key(array('jd'=>$JD[$i],'blazar_id'=>$blazar_id))
                   ->fields($data_entry);
        $query->execute();
    }
  }
  catch (Exception $e) {
    $trans_value->rollback();
    drupal_set_message(t('db_insert failed. Message = %message, query= %query',
      array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
  }
  return $query;
}

/**
 * Save polarimetry entry in the database.
 *
 */
function polar_entry_insert_polar($entry) {
  global $user;
  //check if user allowed to add the database
  if (! in_array("robopol", $user->roles)) {
    drupal_set_message(t('ask Admin to be added to robopol role'), 'error');
    return NULL;
  }
  $IsWithMag = False; //flag to run/not run polar_entry_insert_phot_from_pol()
  $IsWithMagErr = False;
  $n_new_rows = 0;
  $blazar_id = $entry['blazar_name'];
  //parsing data
  $data_arr = preg_split("/((?<!\\\|\r)\n)|((?<!\\\)\r\n)/", $entry['data']);
  foreach ($data_arr as $value) {
    $value = trim ($value);
    if ($value == "") continue;
    $one_line  = preg_split("/[\s,]+/", $value);
    if ( (count($one_line) < 3)||(count($one_line) > 8) ) {
      drupal_set_message(t('Data string length must be >= 3 and <= 8'), 'error');
      return NULL;
    }
    if (count($one_line) > 3){
      //if not "JD P PA" all but one must be numeric
      for ($i = 0; $i < count($one_line)-1; $i += 1) {
        if (!(is_numeric($one_line[$i]))) {
          if (!($one_line[$i]=="NaN")) {
            drupal_set_message(t('Only last data row can be literal.'), 'error');
            return NULL;
          }
        }
      }
    }

    // "JD P PA"
    if (count($one_line) == 3){
      if (!(is_numeric($one_line[0]) &&
            is_numeric($one_line[1]) &&
            is_numeric($one_line[2]))) {
        drupal_set_message(t('It seems that you give not numeric data.'), 'error');
        return NULL;
      }
      $JD[]       = floatval($one_line[0]); //FIXME change it with smart function
      $P[]        = floatval($one_line[1]); //FIXME who understands comma as delimeter
      $PA[]       = floatval($one_line[2]);
      $P_err[]    = 999;
      $PA_err[]   = 999;
      $tel[]      = "Unknown";
    }
    // "JD P PA tel" or "JD m P PA"
    if (count($one_line) == 4){
      if (!(is_numeric($one_line[3]))) {
        $JD[]       = floatval($one_line[0]);
        $P[]        = floatval($one_line[1]);
        $PA[]       = floatval($one_line[2]);
        $P_err[]    = 999;
        $PA_err[]   = 999;
        $tel[]      = $one_line[3];
      }
      else {
        $JD[]       = floatval($one_line[0]);
        $P[]        = floatval($one_line[2]);
        $PA[]       = floatval($one_line[3]);
        $P_err[]    = 999;
        $PA_err[]   = 999;
        $tel[]      = "Unknown";
      }
    }
    // "JD P P_err PA PA_err"
    if (count($one_line) == 5){
      $JD[]       = floatval($one_line[0]);
      $P[]        = floatval($one_line[1]);
      $P_err[]    = floatval($one_line[2]);
      $PA[]       = floatval($one_line[3]);
      $PA_err[]   = floatval($one_line[4]);
      $tel[]      = "Unknown";
    }
    // "JD m P P_err PA PA_err"
    if (count($one_line) == 6){
      $JD[]       = floatval($one_line[0]);
      $P[]        = floatval($one_line[2]);
      $P_err[]    = floatval($one_line[3]);
      $PA[]       = floatval($one_line[4]);
      $PA_err[]   = floatval($one_line[5]);
      $tel[]      = "Unknown";
      $IsWithMag = True;
    }
    // "JD m P P_err PA PA_err tel" or "JD m P P_err PA PA_err FWHM"
    if (count($one_line) == 7){
      if (!(is_numeric($one_line[6]))) {
        $JD[]       = floatval($one_line[0]);
        $P[]        = floatval($one_line[2]);
        $P_err[]    = floatval($one_line[3]);
        $PA[]       = floatval($one_line[4]);
        $PA_err[]   = floatval($one_line[5]);
        $tel[]      = $one_line[6];
      }
      else {
        $JD[]       = floatval($one_line[0]);
        $P[]        = floatval($one_line[2]);
        $P_err[]    = floatval($one_line[3]);
        $PA[]       = floatval($one_line[4]);
        $PA_err[]   = floatval($one_line[5]);
        $tel[]      = "Unknown";
      }
      $IsWithMag = True;
    }
    // "JD m m_err P P_err PA PA_err tel"
    if (count($one_line) == 8){
      if (!(is_numeric($one_line[7]))) {
        $JD[]       = floatval($one_line[0]);
        $P[]        = floatval($one_line[3]);
        $P_err[]    = floatval($one_line[4]);
        $PA[]       = floatval($one_line[5]);
        $PA_err[]   = floatval($one_line[6]);
        $tel[]      = $one_line[7];
      }
      else {
        $JD[]       = floatval($one_line[0]);
        $P[]        = floatval($one_line[3]);
        $P_err[]    = floatval($one_line[4]);
        $PA[]       = floatval($one_line[5]);
        $PA_err[]   = floatval($one_line[6]);
        $tel[]      = "Unknown";
      }
      $IsWithMag = True;
      $IsWithMagErr = True;
    }
    //ready to write or rewrite
    $JDates  = array_values($JD);//just to prevent warnings
    $n_new_rows = $n_new_rows + 1;//WARNING do i really need it
  }

  if($n_new_rows < 1) return NULL;
  $trans_value = db_transaction();
  try {
    //fill data table
    for ( $i = 0; $i < count($JD); $i += 1) {
        $data_entry = array(
          'creator_id'  => $user->uid,
          'blazar_id'   => $blazar_id,
          'jd'          => $JD[$i],
          'p'           => $P[$i],
          'p_err'       => $P_err[$i],
          'pa'          => $PA[$i],
          'pa_err'      => $PA_err[$i],
          'tel'         => $tel[$i],
        );
        $query = db_merge('polar_polar')
                   ->key(array('jd'=>$JD[$i],'blazar_id'=>$blazar_id))
                   ->fields($data_entry);
        $query->execute();
    }
  }
  catch (Exception $e) {
    $trans_value->rollback();
    drupal_set_message(t('db_insert failed. Message = %message, query= %query',
      array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
  }

  if ($IsWithMag) {
    polar_entry_insert_phot_from_pol($entry,$IsWithMagErr);
  }
  return $query;
}

/**
 * Submit handler for 'add entry' form.
 */
function polar_form_add_submit($form, &$form_state) {
  // Save the submitted entry.
  $entry = array(
    'blazar_name' => $form_state['values']['name'],
    'data'        => $form_state['values']['data']
  );
  $return = polar_entry_insert_polar($entry);
  if ($return) {
    //drupal_set_message(t("Created entry @entry", array('@entry' => print_r($entry, TRUE))));
    drupal_set_message(t("Data have been successfully added"));
  }
}

/**
 * @} End of "defgroup polar".
 */
